## Importing initial libraries

In [1]:
import pandas as pd
import numpy as np

## Read the dataset

In [2]:
train_data = pd.read_csv(r"C:\Users\Rohit\datacamp projects\Kaggle- Titanic\train.csv")
test_data = pd.read_csv(r"C:\Users\Rohit\datacamp projects\Kaggle- Titanic\test.csv")

In [3]:
train_data.info()
train_data.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [4]:
test_data.info()
test_data.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  418 non-null    int64  
 1   Pclass       418 non-null    int64  
 2   Name         418 non-null    object 
 3   Sex          418 non-null    object 
 4   Age          332 non-null    float64
 5   SibSp        418 non-null    int64  
 6   Parch        418 non-null    int64  
 7   Ticket       418 non-null    object 
 8   Fare         417 non-null    float64
 9   Cabin        91 non-null     object 
 10  Embarked     418 non-null    object 
dtypes: float64(2), int64(4), object(5)
memory usage: 36.0+ KB


PassengerId  Pclass                                          Name     Sex  \
0          892       3                              Kelly, Mr. James    male   
1          893       3              Wilkes, Mrs. James (Ellen Needs)  female   
2          894       2                     Myles, Mr. Thomas Francis    male   
3          895       3                              Wirz, Mr. Albert    male   
4          896       3  Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female   

    Age  SibSp  Parch   Ticket     Fare Cabin Embarked  
0  34.5      0      0   330911   7.8292   NaN        Q  
1  47.0      1      0   363272   7.0000   NaN        S  
2  62.0      0      0   240276   9.6875   NaN        Q  
3  27.0      0      0   315154   8.6625   NaN        S  
4  22.0      1      1  3101298  12.2875   NaN        S

## Inspecting the missing data

In [5]:
train_data.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [6]:
test_data.isnull().sum()

PassengerId      0
Pclass           0
Name             0
Sex              0
Age             86
SibSp            0
Parch            0
Ticket           0
Fare             1
Cabin          327
Embarked         0
dtype: int64

## Handling the missing data in the training set

we will impute mean values in the age column and will remove the Cabin column since it contains a large number of missing values as compared to the count of rows in the training data. For the missing the data in the embarked column we fill remove the 2 rows with the missing data.

In [7]:
train_data['Cabin'].unique()

array([nan, 'C85', 'C123', 'E46', 'G6', 'C103', 'D56', 'A6',
       'C23 C25 C27', 'B78', 'D33', 'B30', 'C52', 'B28', 'C83', 'F33',
       'F G73', 'E31', 'A5', 'D10 D12', 'D26', 'C110', 'B58 B60', 'E101',
       'F E69', 'D47', 'B86', 'F2', 'C2', 'E33', 'B19', 'A7', 'C49', 'F4',
       'A32', 'B4', 'B80', 'A31', 'D36', 'D15', 'C93', 'C78', 'D35',
       'C87', 'B77', 'E67', 'B94', 'C125', 'C99', 'C118', 'D7', 'A19',
       'B49', 'D', 'C22 C26', 'C106', 'C65', 'E36', 'C54',
       'B57 B59 B63 B66', 'C7', 'E34', 'C32', 'B18', 'C124', 'C91', 'E40',
       'T', 'C128', 'D37', 'B35', 'E50', 'C82', 'B96 B98', 'E10', 'E44',
       'A34', 'C104', 'C111', 'C92', 'E38', 'D21', 'E12', 'E63', 'A14',
       'B37', 'C30', 'D20', 'B79', 'E25', 'D46', 'B73', 'C95', 'B38',
       'B39', 'B22', 'C86', 'C70', 'A16', 'C101', 'C68', 'A10', 'E68',
       'B41', 'A20', 'D19', 'D50', 'D9', 'A23', 'B50', 'A26', 'D48',
       'E58', 'C126', 'B71', 'B51 B53 B55', 'D49', 'B5', 'B20', 'F G63',
       'C62 C64',

In [8]:
train_data['Embarked'].unique()

array(['S', 'C', 'Q', nan], dtype=object)

In [9]:
train_data['Age'].fillna(train_data['Age'].mean(), inplace=True)

In [10]:
train_data = train_data.drop('Cabin', axis=1)

In [11]:
train_data = train_data.dropna()

In [12]:
train_data.isnull().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Embarked       0
dtype: int64

## Preparing data for modelling (PreProcessing)

There are some columns in the data that are of no use for our machine learning model, hence we will get rid of those column in this section.

Also we will be 
1. converting Non-Numeric data into Numeric
2. Label Encoding if required
3. Scale the feature values to a uniform range
4. Split the data into train and test sets

In [13]:
train_data = train_data.drop(['PassengerId', 'Name'], axis=1)

In [14]:
train_data

Survived  Pclass     Sex        Age  SibSp  Parch            Ticket  \
0           0       3    male  22.000000      1      0         A/5 21171   
1           1       1  female  38.000000      1      0          PC 17599   
2           1       3  female  26.000000      0      0  STON/O2. 3101282   
3           1       1  female  35.000000      1      0            113803   
4           0       3    male  35.000000      0      0            373450   
..        ...     ...     ...        ...    ...    ...               ...   
886         0       2    male  27.000000      0      0            211536   
887         1       1  female  19.000000      0      0            112053   
888         0       3  female  29.699118      1      2        W./C. 6607   
889         1       1    male  26.000000      0      0            111369   
890         0       3    male  32.000000      0      0            370376   

        Fare Embarked  
0     7.2500        S  
1    71.2833        C  
2     7.9250        S  
3    53.1000        S  
4     8.0500        S  
..       ...      ...  
886  13.0000        S  
887  30.0000        S  
888  23.4500        S  
889  30.0000        C  
890   7.7500        Q  

[889 rows x 9 columns]

In [15]:
from sklearn.preprocessing import LabelEncoder

la = LabelEncoder()

for col in train_data.columns:
    if train_data[col].dtypes == 'object':
        train_data[col] = la.fit_transform(train_data[col])

In [16]:
train_data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 889 entries, 0 to 890
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Survived  889 non-null    int64  
 1   Pclass    889 non-null    int64  
 2   Sex       889 non-null    int32  
 3   Age       889 non-null    float64
 4   SibSp     889 non-null    int64  
 5   Parch     889 non-null    int64  
 6   Ticket    889 non-null    int32  
 7   Fare      889 non-null    float64
 8   Embarked  889 non-null    int32  
dtypes: float64(2), int32(3), int64(4)
memory usage: 59.0 KB


In [17]:
train_data.head()

Survived  Pclass  Sex   Age  SibSp  Parch  Ticket     Fare  Embarked
0         0       3    1  22.0      1      0     522   7.2500         2
1         1       1    0  38.0      1      0     595  71.2833         0
2         1       3    0  26.0      0      0     668   7.9250         2
3         1       1    0  35.0      1      0      48  53.1000         2
4         0       3    1  35.0      0      0     471   8.0500         2

### Splitting the data into training and test set

In [18]:
from sklearn.model_selection import train_test_split

In [19]:
train_data = train_data.values

In [20]:
X,y = train_data[:,1:9], train_data[:,0]

In [21]:
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=.2, random_state=26)

In [22]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

rescaledX_train = scaler.fit_transform(X_train)
rescaledX_test = scaler.fit_transform(X_test)

## Building the model

In [23]:
rescaledX_train

array([[ 8.33227072e-01,  7.63884108e-01,  3.39050429e-03, ...,
         1.49270670e-01, -4.96543944e-01,  5.97090144e-01],
       [ 8.33227072e-01, -1.30909910e+00, -9.92253005e-01, ...,
        -4.30354930e-01, -4.95932556e-01,  5.97090144e-01],
       [-1.56040706e+00,  7.63884108e-01, -8.35447857e-01, ...,
        -1.19486111e+00,  4.84481736e+00,  5.97090144e-01],
       ...,
       [ 8.33227072e-01,  7.63884108e-01, -9.13850431e-01, ...,
        -2.06195925e-02, -4.99596699e-01,  5.97090144e-01],
       [-1.56040706e+00, -1.30909910e+00,  8.11006194e-01, ...,
        -1.26481592e+00,  2.15428962e+00, -1.90751807e+00],
       [-1.56040706e+00,  7.63884108e-01,  6.54201046e-01, ...,
        -1.18486756e+00, -6.61865881e-01,  5.97090144e-01]])

In [24]:
from sklearn.linear_model import LogisticRegression

le = LogisticRegression()

le.fit(rescaledX_train, y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [25]:
from sklearn.svm import SVC

svm = SVC(kernel = 'linear' , probability = True, random_state = 42)

svm.fit(rescaledX_train, y_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='linear',
    max_iter=-1, probability=True, random_state=42, shrinking=True, tol=0.001,
    verbose=False)

In [37]:
from keras import models
from keras import layers

network = models.Sequential()
network.add(layers.Dense(8, activation='relu', input_dim=8))
network.add(layers.Dense(64, activation='relu'))
network.add(layers.Dense(64, activation='relu'))
network.add(layers.Dense(64, activation='relu'))
network.add(layers.Dropout(0.4))
network.add(layers.Dense(2, activation='softmax')) 

In [27]:
from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier(n_estimators=150)
rf.fit(rescaledX_train, y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=150,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [28]:
x_pred = rf.predict(rescaledX_test)

print("Accuracy of logistic regression classifier: ", rf.score(rescaledX_test, y_test))

Accuracy of logistic regression classifier:  0.8258426966292135


## Making Prediction and evaluating model performance

In [29]:
from sklearn.metrics import confusion_matrix

In [30]:
y_pred = le.predict(rescaledX_test)

print("Accuracy of logistic regression classifier: ", le.score(rescaledX_test, y_test))

confusion_matrix(y_pred,y_test)

Accuracy of logistic regression classifier:  0.7752808988764045


array([[100,  19],
       [ 21,  38]], dtype=int64)

In [31]:
yy_pred = svm.predict(rescaledX_test)

print("Accuracy of SVM classifier: ", svm.score(rescaledX_test, y_test))

confusion_matrix(y_pred,y_test)

Accuracy of SVM classifier:  0.8033707865168539


array([[100,  19],
       [ 21,  38]], dtype=int64)

In [38]:
network.compile(optimizer='adam',
                loss='sparse_categorical_crossentropy',
                metrics=['accuracy'])

In [39]:
network.summary()

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_6 (Dense)              (None, 8)                 72        
_________________________________________________________________
dense_7 (Dense)              (None, 64)                576       
_________________________________________________________________
dense_8 (Dense)              (None, 64)                4160      
_________________________________________________________________
dense_9 (Dense)              (None, 64)                4160      
_________________________________________________________________
dropout_1 (Dropout)          (None, 64)                0         
_________________________________________________________________
dense_10 (Dense)             (None, 2)                 130       
Total params: 9,098
Trainable params: 9,098
Non-trainable params: 0
____________________________________________________

In [40]:
network.fit(rescaledX_train, y_train, epochs=500, verbose=1)

Epoch 1/500
711/711 [==============================] - 2s 2ms/step - loss: 0.6342 - accuracy: 0.6920
Epoch 2/500
711/711 [==============================] - 0s 45us/step - loss: 0.5351 - accuracy: 0.7693
Epoch 3/500
711/711 [==============================] - 0s 45us/step - loss: 0.5116 - accuracy: 0.7637
Epoch 4/500
711/711 [==============================] - 0s 51us/step - loss: 0.4838 - accuracy: 0.7876
Epoch 5/500
711/711 [==============================] - 0s 51us/step - loss: 0.4722 - accuracy: 0.7848
Epoch 6/500
711/711 [==============================] - 0s 45us/step - loss: 0.4656 - accuracy: 0.7961
Epoch 7/500
711/711 [==============================] - 0s 45us/step - loss: 0.4567 - accuracy: 0.7848
Epoch 8/500
711/711 [==============================] - 0s 39us/step - loss: 0.4519 - accuracy: 0.7947
Epoch 9/500
711/711 [==============================] - 0s 45us/step - loss: 0.4408 - accuracy: 0.8031
Epoch 10/500
711/711 [==============================] - 0s 45us/step - loss: 0.4338

711/711 [==============================] - 0s 51us/step - loss: 0.2338 - accuracy: 0.8973
Epoch 160/500
711/711 [==============================] - 0s 51us/step - loss: 0.2334 - accuracy: 0.8973
Epoch 161/500
711/711 [==============================] - 0s 51us/step - loss: 0.2367 - accuracy: 0.9015
Epoch 162/500
711/711 [==============================] - 0s 51us/step - loss: 0.2325 - accuracy: 0.9001
Epoch 163/500
711/711 [==============================] - 0s 51us/step - loss: 0.2342 - accuracy: 0.8987
Epoch 164/500
711/711 [==============================] - 0s 51us/step - loss: 0.2261 - accuracy: 0.9072
Epoch 165/500
711/711 [==============================] - 0s 45us/step - loss: 0.2352 - accuracy: 0.9058
Epoch 166/500
711/711 [==============================] - 0s 51us/step - loss: 0.2445 - accuracy: 0.8903
Epoch 167/500
711/711 [==============================] - 0s 45us/step - loss: 0.2381 - accuracy: 0.9072
Epoch 168/500
711/711 [==============================] - 0s 51us/step - loss: 

711/711 [==============================] - 0s 45us/step - loss: 0.1630 - accuracy: 0.9283
Epoch 316/500
711/711 [==============================] - 0s 51us/step - loss: 0.1676 - accuracy: 0.9311
Epoch 317/500
711/711 [==============================] - 0s 51us/step - loss: 0.1673 - accuracy: 0.9269
Epoch 318/500
711/711 [==============================] - 0s 51us/step - loss: 0.1686 - accuracy: 0.9297
Epoch 319/500
711/711 [==============================] - 0s 45us/step - loss: 0.1574 - accuracy: 0.9339
Epoch 320/500
711/711 [==============================] - 0s 56us/step - loss: 0.1774 - accuracy: 0.9255
Epoch 321/500
711/711 [==============================] - 0s 56us/step - loss: 0.1642 - accuracy: 0.9283
Epoch 322/500
711/711 [==============================] - 0s 56us/step - loss: 0.1601 - accuracy: 0.9269
Epoch 323/500
711/711 [==============================] - 0s 51us/step - loss: 0.1793 - accuracy: 0.9226
Epoch 324/500
711/711 [==============================] - 0s 51us/step - loss: 

711/711 [==============================] - 0s 41us/step - loss: 0.1532 - accuracy: 0.9395
Epoch 472/500
711/711 [==============================] - 0s 45us/step - loss: 0.1539 - accuracy: 0.9311
Epoch 473/500
711/711 [==============================] - 0s 45us/step - loss: 0.1737 - accuracy: 0.9226
Epoch 474/500
711/711 [==============================] - 0s 39us/step - loss: 0.1492 - accuracy: 0.9367
Epoch 475/500
711/711 [==============================] - 0s 39us/step - loss: 0.1483 - accuracy: 0.9409
Epoch 476/500
711/711 [==============================] - 0s 45us/step - loss: 0.1570 - accuracy: 0.9339
Epoch 477/500
711/711 [==============================] - 0s 39us/step - loss: 0.1472 - accuracy: 0.9325
Epoch 478/500
711/711 [==============================] - 0s 39us/step - loss: 0.1543 - accuracy: 0.9325
Epoch 479/500
711/711 [==============================] - 0s 45us/step - loss: 0.1430 - accuracy: 0.9367
Epoch 480/500
711/711 [==============================] - 0s 45us/step - loss: 

In [41]:
test_loss, test_acc = network.evaluate(rescaledX_test, y_test)

178/178 [==============================] - 1s 7ms/step


In [42]:
test_acc

0.7865168452262878

In [43]:
n_pred = network.predict_classes(rescaledX_test)

In [44]:
n_pred

array([0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0,
       1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0,
       1, 1], dtype=int64)

## Test set

In [45]:
test_data.isnull().sum()

PassengerId      0
Pclass           0
Name             0
Sex              0
Age             86
SibSp            0
Parch            0
Ticket           0
Fare             1
Cabin          327
Embarked         0
dtype: int64

In [46]:
test_data['Age'].fillna(test_data['Age'].mean(), inplace=True)

In [47]:
test_data = test_data.drop('Cabin', axis=1)

In [48]:
test_data['Fare'].fillna(test_data['Fare'].mean(), inplace=True)

In [49]:
test_data.shape

(418, 10)

In [50]:
PID = test_data['PassengerId']

In [51]:
test_data = test_data.drop(['PassengerId', 'Name'], axis=1)

In [52]:
for col in test_data.columns:
    if test_data[col].dtypes == 'object':
        test_data[col] = la.fit_transform(test_data[col])

In [53]:
test_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 8 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Pclass    418 non-null    int64  
 1   Sex       418 non-null    int32  
 2   Age       418 non-null    float64
 3   SibSp     418 non-null    int64  
 4   Parch     418 non-null    int64  
 5   Ticket    418 non-null    int32  
 6   Fare      418 non-null    float64
 7   Embarked  418 non-null    int32  
dtypes: float64(2), int32(3), int64(3)
memory usage: 21.4 KB


In [54]:
rescaled_final = scaler.fit_transform(test_data)

In [55]:
final_pred_rf = rf.predict(rescaled_final)

In [56]:
final_pred_nn = network.predict_classes(rescaled_final)

In [57]:
final_pred_le = le.predict(rescaled_final)

In [58]:
final_pred_svm = svm.predict(rescaled_final)

In [59]:
final_pred_rf.astype(int)

array([0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0,
       1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1,
       1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1,
       1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1,
       0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1,
       1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0,
       0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0,

In [60]:
submission = pd.DataFrame({'PassengerId': PID, 'Survived': final_pred_rf.astype(int)})
submission.to_csv(r"C:\Users\Rohit\datacamp projects\Kaggle- Titanic\final_submission.csv", index=False)

In [61]:
submission = pd.DataFrame({'PassengerId': PID, 'Survived': final_pred_nn})
submission.to_csv(r"C:\Users\Rohit\datacamp projects\Kaggle- Titanic\final_submission_nn.csv", index=False)

In [62]:
final_pred_nn

array([0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1,
       1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1,
       1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1,
       1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1,
       0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1,
       0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0,
       1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1,
       1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0,

In [63]:
final_pred_rf

array([0., 0., 0., 0., 1., 0., 1., 0., 1., 0., 0., 0., 1., 0., 1., 1., 0.,
       0., 1., 0., 1., 0., 1., 1., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0.,
       1., 0., 0., 0., 0., 1., 0., 0., 0., 1., 1., 0., 0., 0., 1., 1., 1.,
       0., 1., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 1., 0., 1., 1., 0.,
       0., 1., 1., 0., 0., 0., 1., 0., 0., 1., 0., 0., 1., 0., 0., 0., 0.,
       0., 1., 1., 1., 1., 0., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0.,
       0., 0., 1., 0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 0., 0., 1., 0.,
       1., 1., 0., 1., 0., 0., 1., 0., 1., 0., 0., 1., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.,
       1., 0., 0., 1., 1., 0., 1., 1., 1., 1., 0., 0., 0., 0., 0., 1., 0.,
       0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 0., 0., 1., 0., 1., 0., 1.,
       0., 0., 0., 0., 0., 0., 0., 1., 0., 1., 1., 0., 0., 1., 1., 0., 1.,
       0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 1., 0., 1., 0., 1.,
       0., 1., 0., 1., 1.

In [64]:
final_pred_le

array([0., 0., 0., 0., 1., 0., 1., 0., 1., 0., 0., 0., 1., 0., 1., 1., 0.,
       0., 0., 1., 0., 0., 1., 1., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0.,
       1., 0., 1., 1., 0., 0., 0., 1., 0., 1., 1., 0., 0., 0., 1., 0., 0.,
       0., 1., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 1., 1., 1., 1., 0.,
       1., 1., 1., 0., 1., 1., 1., 1., 0., 1., 0., 1., 0., 0., 0., 0., 0.,
       0., 1., 1., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0.,
       0., 0., 1., 0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 0., 0., 1., 1.,
       1., 1., 0., 1., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 1., 0., 0., 1., 0., 0., 0., 0., 1., 0., 1., 0., 1., 0., 0.,
       0., 0., 0., 1., 1., 0., 1., 1., 0., 1., 0., 0., 1., 0., 0., 1., 1.,
       0., 0., 0., 0., 0., 1., 1., 0., 1., 1., 0., 0., 1., 0., 1., 0., 1.,
       0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 1., 0., 1., 1., 0., 0., 1.,
       0., 1., 1., 0., 1., 0., 0., 0., 0., 1., 0., 0., 1., 0., 1., 0., 1.,
       0., 1., 0., 1., 1.

In [65]:
submission = pd.DataFrame({'PassengerId': PID, 'Survived': final_pred_le.astype(int)})
submission.to_csv(r"C:\Users\Rohit\datacamp projects\Kaggle- Titanic\final_submission_le.csv", index=False)

In [66]:
submission = pd.DataFrame({'PassengerId': PID, 'Survived': final_pred_svm.astype(int)})
submission.to_csv(r"C:\Users\Rohit\datacamp projects\Kaggle- Titanic\final_submission_svm.csv", index=False)

In [74]:
# Import GridSearchCV
from sklearn.model_selection import GridSearchCV

# Define the grid of values for tol and max_iter
tol = [0.1, 0.01, 0.001]
max_iter = [300, 350, 400]

# Create a dictionary where tol and max_iter are keys and the lists of their values are corresponding values
param_grid = dict(tol=tol, max_iter=max_iter)
param_grid

{'tol': [0.1, 0.01, 0.001], 'max_iter': [300, 350, 400]}

In [75]:
# Instantiate GridSearchCV with the required parameters
grid_model = GridSearchCV(estimator=le, param_grid=param_grid, cv=5)

# Use scaler to rescale X and assign it to rescaledX
rescaledX = scaler.fit_transform(X)

# Fit data to grid_model
grid_model_result = grid_model.fit(rescaledX, y)

# Summarize results
best_score, best_params = grid_model_result.best_score_ , grid_model_result.best_params_
print("Best: %f using %s" % (best_score, best_params))

Best: 0.788555 using {'max_iter': 300, 'tol': 0.1}
